name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Generate sitemap
      run: |
        npm install -g sitemap-generator-cli
        sitemap-generator-cli http://www.enigmadm.com -o sitemap.xml

    - name: Commit sitemap
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git commit -m "Generate sitemap"
        git push
